### ISSUE TITLE
Preparando el equipo

### ISSUE THREAD

**Issue by bjrmatos** [reactjs-hispano/react-es-docs#1]
Este issue es con el fin de planear como dividiremos el trabajo de la traducción de la documentación de react a español :tada: 

Para empezar necesitamos saber quienes están dispuestos a colaborar en esta tarea para poder tener una visión de la cantidad del equipo y poder dividir los docs entre todos :smile:

**Comment by calderaro** [comment]
cuenta conmigo!

**Comment by bjrmatos** [comment]
@calderaro :+1: 

comenten los interesados para agregarlos a la org :)

**Comment by carloscuatin** [comment]
cuenta conmigo tambien :dancers:

**Comment by lucy-jimenez** [comment]
Conmigo también!

**Comment by AlejandroSilva** [comment]
listo para la traduccion tal como hablamos por noders :)

**Comment by ghondar** [comment]
cuentan conmigo :+1:

**Comment by bjrmatos** [comment]
Ok, a los que ya nos confirmaron les voy a pedir que compartan este link con cualquier persona que le pueda interesar, el viernes 4 de marzo cerrare este issue y abriré otro discutiendo las actividades que pueda identificar para hacer un reparto entre el equipo.

**Comment by jlgasparrini** [comment]
Vi la propuesta en el channel de noders y me gustaría participar! :D

**Comment by ElirReshi** [comment]
cuenta conmigo!

**Comment by CoericK** [comment]
@bjrmatos acá listo para colaborar en lo que se pueda.

**Comment by AlejandroSilva** [comment]
Creo que el equipo seremos los que estan aca solamente

**Comment by bjrmatos** [comment]
ok, todo listo. porfavor comentar aqui #3 

@ElirReshi te envie tu invitación a la org, acéptala :)

**Comment by GuillermoParedes** [comment]
@bjrmatos  Me gustaria participar. y ayudar en todo lo que se pueda.

**Comment by bjrmatos** [comment]
@GuillermoParedes cool! te envie la invitacion a la ORG, lee el issue #3 y comenta (en el mismo issue #3) que archivo deseas traducir

**Comment by erifranck** [comment]
@bjrmatos  aun estoy a tiempo de colaborar?

**Comment by jlgasparrini** [comment]
Hola @erifranck! Por supuesto que estas invitado a colaborar. Debes pedirle a @bjrmatos que te envie la invitación a la ORG.

Podes revisar el roadmap que se encuentra en #4, elige cualquiera de los archivos que no tengan asignado _CONTRIBUIDOR_, edita el issue y pon tu nombre ahí.
Luego revisa el contenido de los issues #3 y #6 para empezar 😺

**Comment by bjrmatos** [comment]
@erifranck invitación enviada!

**Comment by erifranck** [comment]
genial gracias :D

**Comment by malonecab** [comment]
Yo también me animo!

**Comment by Angarsk8** [comment]
Me animo a colaborar

**Comment by bjrmatos** [comment]
@Angarsk8 te envie la invitación, puedes revisar [este issue](#3) para poder empezar

**Comment by Angarsk8** [comment]
El link no me lleva a ninguna página @bjrmatos

**Comment by bjrmatos** [comment]
@Angarsk8 ups! este es [link](https://github.com/reactjs-hispano/react-es-docs/issues/3)
